controllerManager:
  manager:
    args:
    - --config=/controller_manager_config.yaml
    - --zap-log-level=2
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: us-central1-docker.pkg.dev/k8s-staging-images/lws/lws
      tag: main
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
  podSecurityContext:
    runAsNonRoot: true
  replicas: 2
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
managerConfig:
  controllerManagerConfigYaml: |-
    apiVersion: config.lws.x-k8s.io/v1alpha1
    kind: Configuration
    leaderElection:
      leaderElect: true
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
